### ISSUE TITLE
All cleared nothing saved or working anymore

### ISSUE THREAD

**Issue by masimies** [GM-Alex/user-access-manager#121]
Hi,
Didn't notice before, but after updated new version today to 2.1.0 all access added before has cleared and trying to add them back, nothing is saved. All previous access to pages has now full access.
I did the database update, but even trying to restore old back or deactivate-activate plugin did no difference.
Yes, cleared the site cache, no effect.

Disabling file-lock do not remove htaccess-file either as it has done it before.

Is this happening only to me or have others same kind of issue?

**Comment by GM-Alex** [comment]
Have you performed the database update?

**Comment by masimies** [comment]
Yes i did.
Does it look like that is causing this?

**Comment by GM-Alex** [comment]
No I just didn't see that you already wrote that. If you restore the database you also need to downgrade the plugin if you want to back to 2.0.13. For me everything seems to work fine with the new version. Are you able to create user groups and assign them to posts after the update?

**Comment by GM-Alex** [comment]
But the UAM columns at posts and the UAM settings are shown?

**Comment by WebmasterNbB** [comment]
I have the same error. I delete the plugin and install it new, but i can assign groups to posts

**Comment by masimies** [comment]
Can you add groups to categories also?

**Comment by masimies** [comment]
UAM columns and all other tags are visible. Submitting the access change to db does not working.

**Comment by WebmasterNbB** [comment]
No changes are saved.

**Comment by GM-Alex** [comment]
Ok strange, I setup a new instance or Wordpress and installed the new version and everything works as expected, also with an update to the new version. Could some of you provide me the access to your site (best would be ftp) that I can debug what's happening tonight. You can contact me via mail: alexanderschneider85@gmail.com

**Comment by masimies** [comment]
One moment. I prepare access for you  to my test-site

**Comment by simonnygh** [comment]
This could be related... The new version recreates the primary key using
"ADD PRIMARY KEY (object_id, object_type, group_id, group_type)"
On my server, this causes an error (the table doesn't get updated) yet the update is successful. The total size of these exceeds 1000 bytes (Specified key was too long; max key length is 1000 bytes). The default InnoDB is even less. It is unnecessary and not ideal to have such large index. Why was object_id changed to VARCHAR(64)? is that really necessary? int(11) was using only 4 bytes.

Also, because the database table upgrade query fails, the following code probably fails to, but I wish to understand what it does:

        $update = $this->database->update(
            $dbAccessGroupToObject,
            ['group_type' => UserGroup::USER_GROUP_TYPE],
            ['group_type' => '']
        );

When I upgrade the table manually by tweaking the primary key to fall under 1000, there were still issues, perhaps because above group_type code failed to execute? the group_type column was empty after upgrade. Not sure if it needs to be populated and with what.

Was seeing this from the script, perhaps related to failure to populate the group_type column?

>Fatal error: Uncaught exception
>'UserAccessManager\ObjectMembership\MissingObjectMembershipHandlerException'
>with message 'Missing membership handler for 'product_cat'.' in
>wp-content/plugins/user-access-manager/src/Object/ObjectHandler.php:397
>Stack trace: #0
>wp-content/plugins/user-access-manager/src/UserGroup/AbstractUserGroup.php(583):
>UserAccessManager\Object\ObjectHandler->getObjectMembershipHandler('product_cat')
>#1
>wp-content/plugins/user-access-manager/src/View/GroupSelectionForm.php(42):
>UserAccessManager\UserGroup\AbstractUserGroup->isObjectMember('product_cat',
>NULL, NULL) #2
>wp-content/plugins/user-access-manager/src/View/TermEditForm.php(31):
>include('...') #3
>wp-content/plugins/user-access-manager/src/Wrapper/Php.php(126):
>include('...') #4
>wp-content/plugins/user-access-manager/src/Controller/BaseControllerTrait.php(116):
>UserAccessManager\W in
>wp-content/plugins/user-access-manager/src/Object/ObjectHandler.php
>on line 397

Hope this helps... the primary key is likely the biggest culprit and will affect a number of people that are not running InnoDB with large_prefix enabled, but come on, there is really no reason to create such large index for this :)

**Comment by nicksss93** [comment]
I would like to report the same issue when updating to 2.1. All acess data configured before was lost and all content was set to full access. Worse still, it also broke some parts of the admin panel and when I tried to add the access settings again to some custom post types, I wasn't able to because of some errors showing up - see the following screenshots.

http://store.picbg.net/pubpic/60/1E/89d391c522a9601e.png

http://store.picbg.net/pubpic/DB/65/a9ec471b76eddb65.png

I've updated the plugin and the database. I haven't cleared the cache. I then reverted back to the old database and plugin version (2.0.13), when it worked and I'm currently running that.

**Comment by GM-Alex** [comment]
@simonnygh I think you are right. I reduced the size of the columns to 32. It's necessary because the keys can be strings...
@masimies @WebmasterNbB @nicksss93 @simonnygh Could you guys download version 2.1 from here https://wordpress.org/plugins/user-access-manager/advanced/, replace the `src` folder with the one from here https://github.com/GM-Alex/user-access-manager/archive/master.zip and test again. That would be a great help. Thank you!

**Comment by GM-Alex** [comment]
@simonnygh You where 100% right. Was able to reproduce the problem. New version is coming soon. Thanks to you all!

**Comment by GM-Alex** [comment]
New version is now online, would be nice if someone could also test and give feedback. Thanks a lot.

**Comment by nicksss93** [comment]
Hi Alex,

I've now updated the plugin again to 2.1.2 on a test website to see if it works. It's a bit better than it used to be - more things get loaded, less error messages are shown. However, the majority of the issues are still present:

- after you update the plugin, all custom post types and taxonomies become with full access again. Updating the database doesn't do any difference;
- now the different access groups are loaded and available as options when publishing a post, creating a taxonomy, etc., but your choice of one when publishing or updating the post/taxonomy doesn't get saved and it still stays as full access. Your choice is only saved when you add a user group to a user profile and doesn't work with content pages;
- this error message is shown on top of UAM settings page in every section: "array_fill(): Number of elements must be positive in .../user-access-manager/src/Wrapper/Php.php on line 47"

Hope this helps and you can sort these out.

In the meantime, the time-based user group access is a great idea. Would gladly use it eventually in order to grant access for a specific period of time to a specific user instead of editing it manually, as I do now. Was even thinking of recommending this as a further improvement to the plugin earlier today :) It would really make a difference when it's usable - thanks a lot for your effort!

Hope the other issues would also get fixed so that we could use the plugin flawlessly again. Thanks.

**Comment by masimies** [comment]
Hi,
This issue remains still after updates:
Disabling file-lock do not remove htaccess-file either as it has done it before.

**Comment by GM-Alex** [comment]
@nicksss93 Could you please replace `ROOT/wp-content/plugins/user-access-manager/src/Object/ObjectHandler.php` with this one: https://github.com/GM-Alex/user-access-manager/blob/master/src/Object/ObjectHandler.php

That would be a great help! Thanks a lot.

**Comment by nicksss93** [comment]
Hi,

I've replaced ObjectHandler.php with the one you've specified. It looks as if the plugin now works - user groups are now saved for custom post types and taxonomies and access restrictions work on the website.

However, the error message is still shown at the plugin settings page. Also, I'm not sure if the time-based group assignment works - when you try to specify user group access a given time period, it always gets saved as 30.11.-0001 as a start and end date.

Haven't been able to test if previous access data get lost when updating from 2.0.13 to 2.1.2. Might be able to test it tonight.

Hope this helps.

**Comment by GM-Alex** [comment]
@masimies Should be fixed now, with 2.1.3.
@nicksss93 Same for the other issue.

**Comment by nicksss93** [comment]
Hi Alex,

I'm back here to report that since updating to the latest version, the plugin is now working correctly, as it used to before.

The time-based access setting still doesn't work, though.

Hope this helps.

**Comment by GM-Alex** [comment]
> The time-based access setting still doesn't work, though.
What exactly isn't working?

**Comment by nicksss93** [comment]
The time-based setting is not saved correctly. It always gets saved as 30.11.-0001 as both start and end date, and thus no access is granted.

Also, if you happen to set up time-based access for a user/post etc., you then can't remove it to grant regular access and it stays with the wrong time-access settings.

**Comment by GM-Alex** [comment]
@nicksss93 Could you grant me access to your web site (FTP + Backend User)? That would be nice. You can contact me via mail: alexanderschneider85@gmail.com
