### ISSUE TITLE
Role Access Selection on pages not saving

### ISSUE THREAD

**Issue by bigmanshawn** [GM-Alex/user-access-manager#74]
Selecting which roles have access to a page does not save.  After update a reload of the page will return all roles to unchecked.

**Comment by GM-Alex** [comment]
Roles to a page? Do you mean assigning user groups to pages?

**Comment by choirweb** [comment]
I have a similar problem : 
Previously, when a user had no access to a post, he could not see it. That is because in the settings of the uam, I indicated : hide complete posts if a user has no access. This worked fine.

Now (although that setting did not change, there is no apparant reason) everyone sees the title of the message with in the excerpt a statement that I've put in the general settings of the website under the tab "members only" .

When I check the "manage user user groups" for the uam, the role affiliation for my groups are empty. When I update the checkboxes for the roles again and hit update group, the checkboxes are empty again.
Same happens when I look at the posts : old ones and new ones. The checkboxes for the goups that can access the posts are empty. When I check the box for the group that needs access to a post and I hit update the post,  the checkbox is empty again.

**Comment by masimies** [comment]
If i remembered correctly i had same issue. But after deleted page cache and browser history, it saved.
After group update, it will not refresh page (load headers again). You have to select group settings again. Then you see the correct status.

**Comment by kopfnick** [comment]
I have the same problem (client reported it today):
Go to a page, try to assign access to a group -> page seems to reload when saving, checkbox is set -> F5 reload -> box is unchecked again, content is visible to everyone.

Made a video: https://www.screencast.com/t/PRvi9PjIPz

UAM is the latest version (2.0.9), db update went smoothly...

**Comment by GM-Alex** [comment]
Could someone try to deactivate all other plugins and test again, currently I'm not able to reproduce it. It the behavior is still present it would be nice if I could get access to a test environment (best would be with ftp/sftp access) to debug it.

**Comment by kopfnick** [comment]
I tried deactivating everything except UAM, still no go.
I can give you access, how can i contact you?

**Comment by GM-Alex** [comment]
Best is follow me on twitter, I will contact you there.

**Comment by kopfnick** [comment]
Done...

**Comment by GM-Alex** [comment]
@kopfnick Should be fixed for you. Thanks for your trust. You can now deactivate every login you gave me. I will adjust the plugin and release the version soon. Meanwhile it would be nice if you also could test. Thanks.

**Comment by kopfnick** [comment]
Is it possible that it still does not work for Media?
Tried saving for some PDFs, adminajax.php seems to get called, but nothing is saved...

**Comment by GM-Alex** [comment]
I will check it the next days.

**Comment by choirweb** [comment]
For me the problem is solved. It was an update of the UAM database that was missing.

**Comment by kopfnick** [comment]
@choirweb i tried restoring 1.4 and then running the update process again - this did not fix it for me, but thx for the suggestion!

**Comment by GM-Alex** [comment]
@kopfnick I can confirm the issue. I will fix it with the next version.
